apiVersion: apps/v1
kind: Deployment
metadata:
  name: out-of-sync-app
  labels:
    app: out-of-sync-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: out-of-sync-app
  template:
    metadata:
      labels:
        app: out-of-sync-app
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
