apiVersion: batch/v1
kind: Job
metadata:
  name: out-of-sync-post-sync
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
        - name: drift-generator
          image: bitnami/kubectl:latest
          command:
            - /bin/sh
            - -c
            - |
              kubectl create configmap drift-$(date +%s) --from-literal=drift=1 || true
      restartPolicy: Never
