apiVersion: batch/v1
kind: Job
metadata:
  name: out-of-sync-post-sync
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
        - name: patcher
          image: bitnami/kubectl:latest
          command:
            - /bin/sh
            - -c
            - |
              cat <<EOF > /tmp/deployment.yaml
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: out-of-sync-app
                labels:
                  app: out-of-sync-app
              spec:
                replicas: 2
                selector:
                  matchLabels:
                    app: out-of-sync-app
                template:
                  metadata:
                    labels:
                      app: out-of-sync-app
                  spec:
                    containers:
                    - name: nginx
                      image: nginx:latest
                      ports:
                      - containerPort: 80
              EOF
              kubectl apply -f /tmp/deployment.yaml
      restartPolicy: Never
